# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Import additional configuration files
#
# These configuration files will be loaded in order, replacing values in files
# loaded earlier with those loaded later in the chain. The file itself will
# always be loaded last.
#import:
#  - /path/to/alacritty.yml

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
#env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  #TERM: alacritty

window:
  dimensions:
   columns: 80
   lines: 24

  # Window position (changes require restart)
  #
  # Specified in number of pixels.
  # If the position is not set, the window manager will handle the placement.
  #position:
  #  x: 0
  #  y: 0

  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
   x: 2
   y: 2

  decorations: none

  # Allow terminal applications to change Alacritty's window title.
  dynamic_title: true

scrolling:
  # Maximum number of lines in the scrollback buffer.
  history: 10000

  # Scrolling distance multiplier.
  multiplier: 3

# Font configuration
#  JetBrainsMono Nerd Font/ Hack Nerd Font / Fira Code Nerd Font / Iosevka Nerd Font
font:
  normal:
    family: Iosevka Nerd Font
    style: Regular
  bold:
    family: Iosevka Nerd Font
    style: Bold
  italic:
    family: Iosevka Nerd Font
    style: Italic
  bold_italic:
    family: Iosevka Nerd Font
    style: Bold Italic
  size: 11.5

  offset:
   x: 0
   y: 0

  glyph_offset:
   x: 0
   y: 0

  use_thin_strokes: true

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

schemes:
  # {{{ Base16 Default Dark
  base16_default_dark: &base16_default_dark
    # Default colors
    primary:
      background: '#181818'
      foreground: '#d8d8d8'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '#d8d8d8'
      cursor: '#d8d8d8'

    # Normal colors
    normal:
      black:   '#181818'
      red:     '#ab4642'
      green:   '#a1b56c'
      yellow:  '#f7ca88'
      blue:    '#7cafc2'
      magenta: '#ba8baf'
      cyan:    '#86c1b9'
      white:   '#d8d8d8'

    # Bright colors
    bright:
      black:   '#585858'
      red:     '#ab4642'
      green:   '#a1b56c'
      yellow:  '#f7ca88'
      blue:    '#7cafc2'
      magenta: '#ba8baf'
      cyan:    '#86c1b9'
      white:   '#f8f8f8'
  # }}}

  # {{{
  iceberg: &iceberg
    primary:
      background: '0x161821'
      foreground: '0xd2d4de'
    normal:
      black:   '0x161821'
      red:     '0xe27878'
      green:   '0xb4be82'
      yellow:  '0xe2a478'
      blue:    '0x84a0c6'
      magenta: '0xa093c7'
      cyan:    '0x89b8c2'
      white:   '0xc6c8d1'
    bright:
      black:   '0x6b7089'
      red:     '0xe98989'
      green:   '0xc0ca8e'
      yellow:  '0xe9b189'
      blue:    '0x91acd1'
      magenta: '0xada0d3'
      cyan:    '0x95c4ce'
      white:   '0xd2d4de'
  # }}}

  # {{{
  nord: &nord
     primary:
       background: '0x2E3440'
       foreground: '0xD8DEE9'
     normal:
       black:   '0x3B4252'
       red:     '0xBF616A'
       green:   '0xA3BE8C'
       yellow:  '0xEBCB8B'
       blue:    '0x81A1C1'
       magenta: '0xB48EAD'
       cyan:    '0x88C0D0'
       white:   '0xE5E9F0'
     bright:
       black:   '0x4C566A'
       red:     '0xBF616A'
       green:   '0xA3BE8C'
       yellow:  '0xEBCB8B'
       blue:    '0x81A1C1'
       magenta: '0xB48EAD'
       cyan:    '0x8FBCBB'
       white:   '0xECEFF4'
  # }}}

  # {{{
  one_dark: &one_dark
    primary:
      background: '0x282c34'
      foreground: '0xabb2bf'
    normal:
      # NOTE: Use '0x131613' for the `black` color if you'd like to see
      # black text on the background.
      black:   '0x282c34'
      red:     '0xe06c75'
      green:   '0x98c379'
      yellow:  '0xd19a66'
      blue:    '0x61afef'
      magenta: '0xc678dd'
      cyan:    '0x56b6c2'
      white:   '0xabb2bf'
    bright:
      black:   '0x5c6370'
      red:     '0xe06c75'
      green:   '0x98c379'
      yellow:  '0xd19a66'
      blue:    '0x61afef'
      magenta: '0xc678dd'
      cyan:    '0x56b6c2'
      white:   '0xffffff'
  # }}}

  # {{{
  moonfly: &moonfly
    # Default colors
    primary:
      background:        '#080808'
      foreground:        '#b2b2b2'
      bright_foreground: '#eeeeee'

    # Cursor colors
    cursor:
      text:   '#080808'
      cursor: '#9e9e9e'

    # Selection colors
    selection:
      text:       '#080808'
      background: '#b2ceee'

    # Normal colors
    normal:
      black:   '#323437'
      red:     '#ff5454'
      green:   '#8cc85f'
      yellow:  '#e3c78a'
      blue:    '#80a0ff'
      magenta: '#d183e8'
      cyan:    '#79dac8'
      white:   '#a1aab8'

    # Bright colors
    bright:
      black:   '#7c8f8f'
      red:     '#ff5189'
      green:   '#36c692'
      yellow:  '#bfbf97'
      blue:    '#74b2ff'
      magenta: '#ae81ff'
      cyan:    '#85dc85'
      white:   '#e2637f'
  # }}}

colors: *iceberg

  # Indexed Colors
  #
  # The indexed colors include all colors from 16 to 256.
  # When these are not set, they're filled with sensible defaults.
  #
  # Example:
  #   `- { index: 16, color: '#ff00ff' }`
  #
  #indexed_colors: []

# Bell
# The bell is rung every time the BEL control character is received.
bell:
  animation: EaseOutExpo
  duration: 50
  color: '#f2b8c5'

background_opacity: 0.9

selection:
  # This string contains all characters that are used as separators for "semantic words" in Alacritty.
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

cursor:
  style: Block
  unfocused_hollow: true
  # thickness: 0.1

# Live config reload (changes require restart)
live_config_reload: true

# Send ESC (\x1b) before characters when alt is pressed.
alt_send_esc: true

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: true

# Mouse bindings
mouse_bindings:
 - { mouse: Middle, action: PasteSelection }

# Key bindings
key_bindings:
  - { key: V,         mods: Control|Shift,          action: Paste }
  - { key: C,         mods: Control|Shift,          action: Copy  }

debug:
  persistent_logging: false
