# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Import additional configuration files
#
# These configuration files will be loaded in order, replacing values in files
# loaded earlier with those loaded later in the chain. The file itself will
# always be loaded last.
import:
  - ~/dotfiles/config/alacritty/themes/uya.yml
  # - ~/dotfiles/config/alacritty/themes/materialocean.yml
  # - ~/dotfiles/config/alacritty/themes/tokionight.yml
  # - ~/dotfiles/config/alacritty/themes/onedark.yml

env:
  TERM: 'xterm-256color'

window:
  dimensions:
   columns: 80
   lines: 24

  padding:
   x: 2
   y: 2

  decorations: none
  dynamic_title: true

  # Background opacity
  #
  # Window opacity as a floating point number from `0.0` to `1.0`.
  # The value `0.0` is completely transparent and `1.0` is opaque.
  opacity: 0.6

scrolling:
  history: 10000
  multiplier: 3

# Font configuration
#  JetBrainsMono Nerd Font/ Hack Nerd Font / Fira Code Nerd Font / Iosevka Nerd Font
font:
  normal:
    family: Victor Mono Nerd Font
    style: Regular
  bold:
    family: Iosevka Nerd Font
    style: Bold
  italic:
    family: Iosevka Nerd Font
    style: Italic
  size: 10.0

  offset:
   x: 0
   y: 0

  glyph_offset:
   x: 0
   y: 0

  use_thin_strokes: true

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

schemes:
  # {{{ Base16 Default Dark
  base16_default_dark: &base16_default_dark
    # Default colors
    primary:
      background: '#181818'
      foreground: '#d8d8d8'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '#d8d8d8'
      cursor: '#d8d8d8'

    # Normal colors
    normal:
      black:   '#181818'
      red:     '#ab4642'
      green:   '#a1b56c'
      yellow:  '#f7ca88'
      blue:    '#7cafc2'
      magenta: '#ba8baf'
      cyan:    '#86c1b9'
      white:   '#d8d8d8'

    # Bright colors
    bright:
      black:   '#585858'
      red:     '#ab4642'
      green:   '#a1b56c'
      yellow:  '#f7ca88'
      blue:    '#7cafc2'
      magenta: '#ba8baf'
      cyan:    '#86c1b9'
      white:   '#f8f8f8'
  # }}}

  # {{{
  iceberg: &iceberg
    primary:
      background: '0x161821'
      foreground: '0xd2d4de'
    normal:
      black:   '0x161821'
      red:     '0xe27878'
      green:   '0xb4be82'
      yellow:  '0xe2a478'
      blue:    '0x84a0c6'
      magenta: '0xa093c7'
      cyan:    '0x89b8c2'
      white:   '0xc6c8d1'
    bright:
      black:   '0x6b7089'
      red:     '0xe98989'
      green:   '0xc0ca8e'
      yellow:  '0xe9b189'
      blue:    '0x91acd1'
      magenta: '0xada0d3'
      cyan:    '0x95c4ce'
      white:   '0xd2d4de'
  # }}}

  # {{{
  nord: &nord
    primary:
      background: '#2E3440'
      foreground: '#D8DEE9'

    # Normal colors
    normal:
      black:   '#3B4252'
      red:     '#BF616A'
      green:   '#A3BE8C'
      yellow:  '#EBCB8B'
      blue:    '#81A1C1'
      magenta: '#B48EAD'
      cyan:    '#88C0D0'
      white:   '#E5E9F0'

    # Bright colors
    bright:
      black:   '#4C566A'
      red:     '#BF616A'
      green:   '#A3BE8C'
      yellow:  '#EBCB8B'
      blue:    '#81A1C1'
      magenta: '#B48EAD'
      cyan:    '#8FBCBB'
      white:   '#ECEFF4'
  # }}}

  # {{{
  moonfly: &moonfly
    # Default colors
    primary:
      background:        '#080808'
      foreground:        '#b2b2b2'
      bright_foreground: '#eeeeee'

    # Cursor colors
    cursor:
      text:   '#080808'
      cursor: '#9e9e9e'

    # Selection colors
    selection:
      text:       '#080808'
      background: '#b2ceee'

    # Normal colors
    normal:
      black:   '#323437'
      red:     '#ff5454'
      green:   '#8cc85f'
      yellow:  '#e3c78a'
      blue:    '#80a0ff'
      magenta: '#d183e8'
      cyan:    '#79dac8'
      white:   '#a1aab8'

    # Bright colors
    bright:
      black:   '#7c8f8f'
      red:     '#ff5189'
      green:   '#36c692'
      yellow:  '#bfbf97'
      blue:    '#74b2ff'
      magenta: '#ae81ff'
      cyan:    '#85dc85'
      white:   '#e2637f'
  # }}}

  # {{{
  # material ocean color scheme
  material_ocean: &material_ocean
    primary:
      background: '0x0f111a'
      foreground: '0xD8DEE9'
    cursor:
      cursor: '0xff4151'
    normal:
      black:      '0x4C566A'
      red:        '0xBF616A'
      green:      '0xA3BE8C'
      yellow:     '0xEBCB8B'
      blue:       '0x81A1C1'
      magenta:    '0xB48EAD'
      cyan:       '0x88C0D0'
      white:      '0xE5E9F0'
  # }}}

# colors: *material_ocean

# Bell
bell:
  animation: EaseOutExpo
  duration: 50
  color: '#f2b8c5'

selection:
  # This string contains all characters that are used as separators for "semantic words" in Alacritty.
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

cursor:
  style: Block
  unfocused_hollow: true
  # thickness: 0.1

# Live config reload (changes require restart)
live_config_reload: true

# Send ESC (\x1b) before characters when alt is pressed.
alt_send_esc: true

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: true

# Mouse bindings
mouse_bindings:
 - { mouse: Middle, action: PasteSelection }

# Key bindings
key_bindings:
  - { key: V,         mods: Control|Shift,          action: Paste }
  - { key: C,         mods: Control|Shift,          action: Copy  }

debug:
  persistent_logging: false
