#!/usr/bin/env bash

# Install dotfiles symlinks.
set -e

DOTFILES="$HOME/dotfiles"

msg() {
  printf '%b\n' "$1" >&2
}

success() {
  if [ "$ret" -eq '0' ]; then
    msg "\\033[32m[✔]\\033[0m ${1}${2}"
  fi
}

warning(){
  msg "\033[33mWarning:\033[0m ${1}${2}"
}

bkp(){
  if [ -e "$1" ];then
    rm -rf "$2"
    mv "$1" "$2"
  fi
}

echo -e "\nCreating dotfile symlinks"

# Setup bash.d directory
if [ ! -d "$HOME/.bash.d" ]; then
  mkdir -p "$HOME/.bash.d"
fi

if [ ! -d "$HOME/bin" ]; then
  mkdir -p "$HOME/bin"
fi

if [ ! -d "$HOME/.emacs.d" ]; then
  mkdir -p "$HOME/.emacs.d"
fi

# bashes config
create_bash_links() {
  for f in "${DOTFILES}"/system/bash.d/*; do
    ln -sfn  "$f"  ~/.bash.d
  done
}

create_bin_links() {
  for file in "$DOTFILES"/bin/*; do
    name="$(basename ${file%%.*})"
    target="$HOME/bin/$name"

    cp -n "$file" "$target"
    chmod +x "$target"
  done
}

create_ruby_links() {
  for f in "${DOTFILES}"/system/ruby/*; do
    filename=".$(basename ${f})"
    ln -sfn  "$f"  "$HOME/$filename"
  done
}

# Config
echo -e "\nCreating config symlinks"
mkdir -p ~/.config
mkdir -p ~/dotfiles_backup/config

for d in "${DOTFILES}"/config/* ; do
  filename=$(echo "$d" | rev | cut -d"/" -f 1 | rev)
  echo "${filename}"

  bkp ~/.config/"$filename" ~/dotfiles_backup/config
  ln -s "$d" ~/.config/
done

# Emacs Config
ln -sfn "$DOTFILES/system/emacs/init.el" "$HOME/.emacs.d/init.el"

# Git and Hub config
ln -sfn "$DOTFILES/system/git/gitconfig" ~/.gitconfig

# mkdir -p ~/.sbt/1.3.10/plugins
# ln -s "$DOTFILES/system/scala/sbtplugins.sbt" ~/.sbt/1.3.10/plugins/dotfileplugins.sbt

if [ ! -f "$HOME/.cargo/config" ]; then
	mkdir -p ~/.cargo && ln -sfn "$DOTFILES/config/cargo/config" "$HOME/.cargo/config"
fi

create_bash_links
create_bin_links
create_ruby_links

ret="$?"
success "Dotfiles have been configured! 🤘"
