#!/usr/bin/env bash

asdf plugin-add swiprolog https://github.com/mracos/asdf-swiprolog.git
asdf plugin-add java https://github.com/halcyon/asdf-java.git
asdf plugin-add clojure https://github.com/halcyon/asdf-clojure.git
asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
asdf plugin-add lua https://github.com/Stratus3D/asdf-lua.git
asdf plugin-add rust https://github.com/code-lever/asdf-rust.git
