#!/usr/bin/env bash
# Set default channel
# rustup default <stable> | <nightly>

RUST_VERSION=1.31.0

asdf install rust $RUST_VERSION

rustup self update
rustup update stable
rustup component add clippy
rustup component add rustfmt

rustup component add rust-src
rustup component add rust-analysis
rustup component add rls-preview
rustup component add rustfmt-preview

# Racer - code completion for Rust use nightly
cargo uninstall racer 2> /dev/null
rustup toolchain add nightly
cargo +nightly install racer

# Enable tab completion for Bash
rustup completions bash > $(brew --prefix)/etc/bash_completion.d/rustup.bash-completion
asdf reshim rust
