#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
# Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

# set horizontal tiling as default
hc set_layout horizontal

feh --no-fehbg --bg-scale ~/dotfiles/config/wallpapers/b3k2w.jpg

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn alacritty

# Apps
hc keybind $Mod-w       spawn firefox
hc keybind $Mod-Mod1-c  spawn chromium
hc keybind $Mod-Mod1-e  spawn neomutt
hc keybind $Mod-Mod1-n  spawn alacritty -e newsboat
hc keybind $Mod-Mod1-w  spawn alacritty -e weechat
hc keybind $Mod-Mod1-t  spawn alacritty -e tmux
hc keybind $Mod-d       spawn dmenu_run -l \
  6 -fn "Hack Nerd Font 1M:size=18" -nb '#212121' \
  -nf '#b3e5fc' -sb black -sf '#f7f7f7' -p '>'

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left   +$resizestep
hc keybind $Mod-Control-j       resize down   +$resizestep
hc keybind $Mod-Control-k       resize up     +$resizestep
hc keybind $Mod-Control-l       resize right  +$resizestep
hc keybind $Mod-Control-Left    resize left   +$resizestep
hc keybind $Mod-Control-Down    resize down   +$resizestep
hc keybind $Mod-Control-Up      resize up     +$resizestep
hc keybind $Mod-Control-Right   resize right  +$resizestep

# tags
#tag_names=("  " "  " "  " "  " "  " "   " "   " "  " "  " "  " )
# tag_names=( {WEB,CODE,TERM,EMAIL,CHAT,FILE,MEDIA,PANEL,MISC} )

tag_names=( " " "   " "   " "" " " " " " " )
# tag_names=( {1..7} )
tag_keys=( {1..7} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period        use_index +1 --skip-visible
hc keybind $Mod-comma         use_index -1 --skip-visible
hc keybind $Mod-bracketright  use_index +1 --skip-visible
hc keybind $Mod-bracketleft   use_index -1 --skip-visible
hc keybind Mod1-Right         use_index +1 --skip-visible
hc keybind Mod1-Left          use_index -1 --skip-visible

# layouting
hc keybind $Mod-r       remove
hc keybind $Mod-s       floating toggle
hc keybind $Mod-f       fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-p       pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#ffffff'
hc set frame_border_normal_color '#4c566a'
hc set frame_bg_normal_color '#4c566a'
hc set frame_bg_active_color '#ffffff'
hc set frame_border_width 0
hc set always_show_frame on
hc set frame_bg_transparent on
hc set frame_transparent_width 1
hc set frame_gap 0

hc attr theme.active.color '#FFFFFF'
hc attr theme.normal.color '#4c566a'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 4
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#4c566a'
hc attr theme.active.outer_color '#ffffff'
hc attr theme.background_color '#4c566a'

hc set window_gap 10
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# window-tag rules
hc rule class~'(firefox|chromium|Google-chrome)' tag='1' switchtag=on focus=on
hc rule class~'alacritty'         tag='2' focus=on
hc rule class~'(Evolution|Geary)' tag='5' focus=on
hc rule class~'vlc'               tag='6' focus=on

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done

# Launch polybar
pkill polybar || true
~/.config/polybar/launch.sh
